# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dhruv Sharma
tagline:          'A website'
description:      'A website for various IB Notes etc.'
url:              https://www.dhruvs.com
baseurl:          

author:
  name:           'Dhruv Sharma'
  url:

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/DhruvSkyy/DhruvSkyy.github.io

social:
    linkedin: https://www.linkedin.com
    twitter: https://twitter.com

# Features
excerpt_separator: <!--more-->
